[api]
OPENAI_API="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"
GEMINI_API="AIzaSyB-jlnKF9WIG7mM4c5MfWZ5dSlBMDYKA68"
